[package]
name = "scopie"
version = "0.1.0"
authors = ["khyperia <khyperia@live.com>"]
edition = "2018"

[dependencies]
failure = { version = "", default-features = false }
gl = { version = "", default-features = false }
khygl = { path = "../khygl", default-features = false }
lazy_static = { version = "", default-features = false }
png = ""
regex = { version = "", default-features = false }
serialport = { version = "", default-features = false }
time = { version = "", default-features = false }