[package]
name = "scopie"
version = "0.1.0"
authors = ["khyperia <khyperia@live.com>"]
edition = "2018"

[dependencies]
failure = ""
gl = ""
khygl = {path = "../khygl"}
lazy_static = ""
regex = ""
serialport = ""
time = ""