[package]
name = "scopie"
version = "0.1.0"
authors = ["khyperia <khyperia@live.com>"]
edition = "2018"

[dependencies]
lazy_static = ""
regex = ""
serialport = ""
time = ""
failure = ""

[dependencies.sdl2]
version = ""
default-features = false
features = ["ttf"]